stages:
  - deploy

deploy_to_vps:
  stage: deploy
  only:
    - main # Trigger this job only for the main branch
  before_script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | base64 -d > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H 87.106.216.52 >> ~/.ssh/known_hosts
  script:
    - ssh -i ~/.ssh/id_rsa root@87.106.216.52 'mkdir -p /var/www/kritzel'
    - scp -i ~/.ssh/id_rsa -r ./* root@87.106.216.52:/var/www/kritzel
    - ssh -i ~/.ssh/id_rsa root@87.106.216.52 'cd /var/www/kritzel && docker-compose up -d --build'
    - ssh -i ~/.ssh/id_rsa root@87.106.216.52 'docker image prune -f'
  environment:
    name: production
    url: http://kritzel.lol
