services:
  app:
    build: .
    volumes:
      - ./app:/app:cached
    ports:
      - "8123:8123"
    environment:
      - NODE_ENV=development
    command: ["sh", "-c", "cp /scripts/entrypoint.sh /app/entrypoint.sh && sh /app/entrypoint.sh"]