@startuml CDBackend
class Kritzel {
    - server: TinyServer
    - game: ServerGame
    + receive(uid: string, message: Message)
    + receiveServerRequest(request: Message)
}

class TinyServer {
    - clients: ClientList
    - wsCallback: function
    - wssCallback: function
    - server: http.Server
    - websocketServer: ws.WebSocketServer
    + constructor(port: int, wsCallback: function, wssCallback: function)
    + connectWs(websocket: WebSocket, request: http.IncomingMessage)
    + getUniqueID(): string
    + processWsRequest(websocket: WebSocket, data: string)
    + processWssRequest(request: Message)
    + broadcastWsMessage(cid: string, data: string, isBinary: boolean, broadcastType: string, clientsInLobby: Client[])
    + processHttpRequest(req: http.IncomingMessage, res: http.ServerResponse)
    + getClients(): ClientList
}

class ServerGame {
    - server: TinyServer
    - lobbies: Lobby[]
    - intervalReference: NodeJS.Timeout
    - tickCallback: function
    + constructor(server: TinyServer, tickCallback: function)
    + start()
    + stop()
    + tick()
    + getLobbies(): Lobby[]
    + processInput(cid: string, request: Message)
    + processServerRequest(request: Message)
    - processDrawAction(action: Object, cid: string, lobbyID: int)
    - processGetCanvasAction(cid: string, lobbyID: int)
    - processChatAction(chatMsg: string, cid: string, timestamp: Date, lobbyID: int)
    - processGetChatAction(cid: string, lobbyID: int)
    - processGetUserListAction(cid: string, lobbyID: int)
    - processSetWordAction(cid: string, word: string, lobbyID: int)
    - processGetReconnectData(cid: string, lobbyID: int)
    - processCreateLobbyAction(client: Client, isPublic: boolean, code: string, lobbyName: string, roundCount: int, roundTimer: int, playerCount: int)
    - processJoinLobbyAction(client: Client, lobbyID: int, code: string)
    - processJoinRandomLobbyAction(client: Client)
    - processLeaveLobbyAction(client: Client)
    - processGetLobbyListAction(cid: string)
    - processDeleteLobbyAction(lobbyID: int)
    - processGetMenuAction(cid: string, broadcastType: string)
    - processShowLobbyContentAction(cid: string)
    - processSendJoinLobbyData(cid: string, lobbyID: int)
    - processSetUserName(client: Client, name: string)
}

class Lobby {
    - playerList: Client[]
    - board: Board
    - chat: Chat
    - game: Game
    - server: TinyServer
    + constructor(server: TinyServer)
    + startGame()
    + addPlayer(player: Client)
    + deletePlayer(cid: string)
    + getPlayerList(): Client[]
    + draw(x: int, y: int, color: int, thickness: int, cid: string)
    + erase(x: int, y: int, thickness: int, cid: string)
    + fill(x: int, y: int, color: int, cid: string): boolean
    + clear(cid: string)
    + getBoardCanvas(): int[][]
    + getBoard(): Board
    + addMessage(message: string, cid: string, timestamp: Date)
    + getMessages(cid: string): {uid: string, msg: string}[]
    + sendUserList()
    + setWord(word: string, cid: string)
    + sendReconnectData(cid: string)
}

class Board {
    - canvas: int[][]
    - rows: int
    - columns: int
    - initialColor: int
    - backgroundColor: int
    - previousPoint: {x0: int, y0: int}
    - points: {x: int, y: int, color: int}[]
    + constructor(columns: int, rows: int, initialColor: int)
    + draw(x: int, y: int, color: int, thickness: int)
    + erase(x: int, y: int, thickness: int)
    + clear()
    + fillBackground(color: int)
    + fill(x: int, y: int, color: int): boolean
    + iterativefill(x: int, y: int, color: int, previousColor: int)
    + getBoard(): int[][]
    + getPoints(): {x: int, y: int, color: int}[]
    + setPointsEmpty()
    - drawLine(x0: int, y0: int, x1: int, y1: int, color: int, thickness: int): {x: int, y: int, color: int}[]
    - drawPoint(x: int, y: int, color: int, thickness: int): {x: int, y: int, color: int}[]
    - setWholeBoard(color: int)
}

class Chat {
    - messages: {cid: string, msg: string, timestamp: Date}[]
    + constructor()
    + addMessage(cid: string, message: string, timestamp: Date)
    + getMessages(): {cid: string, msg: string, timestamp: Date}[]
}

class ClientList {
    - clientList: Client[]
    + constructor()
    + addClient(cid: string, name: string, lobby: int): Client
    + replaceCid(oldCid: string, newCid: string)
    + getClientList(): Client[]
    + registerName(cid: string, name: string)
    + getNameByCid(cid: string): string
}

class Client {
    - cid: string
    - name: string
    - points: int
    - lobbyID: int
    - isConnected: boolean
    + constructor(cid: string, name: string, lobbyID: int)
    + getCid(): string
    + setCid(cid: string)
    + getName(): string
    + setName(name: string)
    + getPoints(): int
    + setPoints(points: int)
    + getLobbyID(): int
    + getIsConnected(): boolean
    + setIsConnected(isConnected: boolean)
}

class Game {
    - playerList: Client[]
    - playerQueue: Client[]
    - state: int
    - word: string
    - totalCycle: int
    - currentCycle: int
    - currentRound: int
    - drawer: Client
    - wordTimeout: int
    - roundTimeout: int
    - nextRoundTimeout: int
    - timeleft: int
    - wordChoicesCount: int
    - wordChoicesList: string[]
    - server: TinyServer
    - answerTimeList: {cid: string, timestamp: Date}[]
    - dictionary: Dictionary
    - wordSelectionTimer: Interval
    - board: Board
    - wordCheckAccuracyRate: float
    - maxPointsGuesser: int
    - maxPointsDrawer: int
    + constructor(server: TinyServer, board: Board)
    + startGame(playerList: Client[], totalCycle: int)
    - startRound()
    - selectDrawer()
    - selectWord()
    - startDrawAndGuess()
    - endRound()
    - endGame()
    + getState(): string
    - nextState()
    + getDrawer(): Client
    + hasPermissionToDraw(cid: string): boolean
    + setWord(word: string, cid: string)
    + checkGameNotStarted(): boolean
    + checkAnswer(answer: string): boolean
    + addAnswer(cid: string, timestamp: Date, chat: Chat)
    + sendUserList(playerList: Client[])
    + sendReconnectData(cid: string)
    - sendWordChoicesList()
    - sendRemoveWordChoicesList()
    - sendWordChoicesNotification(broadcastType: string)
    - sendWord(word: string, broadcastType: string, cid: string?)
    - sendHangManWord()
    - sendTimer(timerType: string, time: string)
    - sendDrawPermission(isEnabled: boolean)
}

class Dictionary {
    - wordList: string[]
    + constructor()
    + getWords(qty: int): string[]
    + removeWord(word: string)
}

package responseTypes {
    enum responseType
}

package requestTypes {
    enum requestType
}

package broadcastTypes {
    enum broadcastType
}

Kritzel --> TinyServer
Kritzel --> ServerGame
' Kritzel --> responseTypes
' TinyServer --> responseTypes
' TinyServer --> requestTypes
' TinyServer --> broadcastTypes
TinyServer --> ClientList
' ServerGame --> responseTypes
' ServerGame --> requestTypes
' ServerGame --> broadcastTypes
ServerGame --> TinyServer
ServerGame --> Lobby
ServerGame --> Client
Lobby --> Board
Lobby --> Chat
Lobby --> Game
Lobby --> Client
Game --> Client
Game --> Dictionary
' Game --> broadcastTypes
' Game --> responseTypes
ClientList --> Client
@enduml
