@startuml CDFrontend

class ClientGame {
  - #name: string
  - #translator: Translator
  - #currentLanguage: string
  - canDraw: boolean
  - lobbyList: Lobby[]
  - socket: WebSocket
  - userList: User[]
  + constructor()
  + openWebSocket(): void
  + setUserList(data: User[]): void
  + setSessionCookie(cid: string): void
  + updateWithPoints(data: {x: number, y: number, color: string, thickness: number}[]): void
  + update(data: string[][]): void
  + sendDrawAction(tool: string, x: number, y: number, color: string, thickness: number): void
  + sendClearAction(): void
  + sendFillAction(x: number, y: number, color: string): void
  + sendGetCanvasAction(): void
  + sendChatAction(chatMessage: string): void
  + sendGetChatAction(): void
  + sendNameAction(name: string): void
  + sendGetUserListAction(): void
  + sendGetReconnectDataAction(): void
  + sendWordAction(word: string): void
  + sendGameStartAction(): void
  + sendJoinLobbyAction(lobbyID: number, code: string): void
  + sendJoinRandomLobbyAction(): void
  + sendLeaveLobbyAction(): void
  + sendCreateLobbyAction(isPublic: boolean, code: string, lobbyName: string, roundCount: number, roundTimer: number, playerCount: number): void
  + sendGetLobbyListAction(): void
  + send(message: string): void
  + setDrawingState(canDraw: boolean): void
  + getCanDraw(): boolean
  + setCanDraw(value: boolean): void
  + updateToolbarVisibility(): void
  + setLanguage(language: string): void
  + renderWordChoice(words: string[]): void
  + translateUI(): void
}

class Message {
  +messageType: string
  +messageBody: DrawAction | ChatAction
  +constructor(messageType: string, messageBody: any)
}

class DrawAction {
  +tool: string
  +x: number
  +y: number
  +color: number
  +thickness: number
  +constructor(tool: string, x: number, y: number, color: number, thickness: number)
}

class UserInterface {
  +renderUsers(users: User[]): void
  +renderWordChoice(words: string[], client: ClientGame): void
  +renderTimer(timerData: any): void
  +displayChatMessage(chatMessages: HTMLElement, message: string, senderName: string, isServerMessage: boolean): void
  +displayChatMessageList(chatMessages: HTMLElement, messageList: ChatMessage[]): void
  +initializeChat(clientGame: ClientGame, sendButton: HTMLElement, chatInputDiv: HTMLElement, chatMessages: HTMLElement): void
}

class Chat {
  +sendMessage(): void
  +displayChatMessage(message: string, sender: string): void
  +displayChatMessageList(messageList: ChatMessage[], clientId: string): void
}

class Toolbar {
  +initializeToolbar(options: object): void
  +onPenSizeChange(newSize: number, button: HTMLButtonElement): void
  +onPenColorChange(newColor: string, button: HTMLButtonElement): void
  +onToolChange(selectedTool: string, button: HTMLButtonElement): void
  +onClearCanvas(): void
}

class VirtualKeyboard {
  +initializeVirtualKeyboard(chatInstance: Chat): void
  +showKeyboard(): void
  +hideKeyboard(): void
  +setChatInputEditable(): void
  +isMobile(): boolean
}

class User {
  -name: string
  -points: number
  -isDrawer: boolean
}

class ChatMessage {
  -cid: string
  -msg: string
}

class Main {
  +initializeCanvasContext(): void
  +resizeCanvas(): void
  +debounce(func: function, wait: number): function
  +startDrawing(event: Event): void
  +stopDrawing(): void
  +draw(event: Event): void
  +getPointerPosition(event: Event): {x: number, y: number}
}

class HexColorConverter {
  +hexToInt(hex: string): number
  +intToHex(int: number): string
}

class Translator {
  -_tokenPattern: RegExp
  -_translations: object
  +translate(text: string, language: string): string
  +getTokenPattern(): RegExp
}

ClientGame --> Message
ClientGame --> DrawAction
ClientGame --> Translator
ClientGame --> HexColorConverter
ClientGame --> UserInterface
ClientGame --> User
ClientGame --> Chat
ClientGame --> Toolbar
ClientGame --> VirtualKeyboard

Message --> DrawAction

UserInterface --> User
UserInterface --> ChatMessage
Chat --> ChatMessage

Main --> ClientGame
Main --> UserInterface
Main --> Chat
Main --> Toolbar
Main --> VirtualKeyboard

@enduml
